### ISSUE TITLE
🐛 Bug Report: Something went wrong when uploading a logo via URL

### ISSUE THREAD

**Issue by txwgnd** [pocket-id/pocket-id#1009]
### Reproduction steps

Hello All,

just updated Pocket-ID to 1.13.0 from 1.10.0. I wanted to checkout the new logo upload via url feature but it fails.
When I upload a logo via url e.g. `https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/svg/homarr.svg` I'll get a popup that's reading "Something went wrong" after clicking on save. The logo does populate correctly after pasting the link into the field though. I tried creating a new client from scratch and to edit existing ones but the error remains the same.

### Expected behavior

Pocket-ID should save the client correctly after pressing save.

### Actual Behavior

After pasting the logo link into the corresponding field, the logo box get's populated with the correct image, but pressing save results in an error message reading "Something went wrong"

### Pocket ID Version

1.13.0 ( Updated from 1.10.0 )

### Database

SQLite

### OS and Environment

TrueNAS Scale 25.04

### Log Output

Browser console is outputting this:

> DnwYoGjf.js:3  PUT https://my.domain.de/api/oidc/clients/af8af299-f66a-4773-92dc-bf2e238acde9 500 (Internal Server Error)
> (anonymous) @ DnwYoGjf.js:3
> xhr @ DnwYoGjf.js:3
> Ie @ DnwYoGjf.js:5
> _request @ DnwYoGjf.js:6
> request @ DnwYoGjf.js:5
> (anonymous) @ DnwYoGjf.js:6
> (anonymous) @ DnwYoGjf.js:1
> updateClient @ BWM1jjVm.js:1
> I @ 18.DeSrqKmJ.js:20
> C @ B9pIfVn9.js:1
> (anonymous) @ B1ASiaS-.js:1
> (anonymous) @ B9pIfVn9.js:1
> (anonymous) @ DcUXUI2v.js:1
> fn @ DcUXUI2v.js:1
> a @ DcUXUI2v.js:1

<img width="1287" height="865" alt="Image" src="https://github.com/user-attachments/assets/63325329-8070-40c2-a943-3c283ac0f8ea" />

**Comment by indero** [comment]
I have the same problem and found out that the image is created as a folder on disk, when using the URL upload method.
Overwriting via upload is also not possible. Only removing the folder manually and uploading the icon manually worked for me.

**Comment by stonith404** [comment]
Thanks, this should be fixed in `v1.13.1`. You may need to delete the created folder manually.

**Comment by BobWs** [comment]
Still having the same problem on the latest (1.14.1) the icon shows after entering the URL, but the disappear after saving.
Tried it with local URL to my own nginx server and https://dashboardicons.com/icons/pgadmin.

**Comment by txwgnd** [comment]
> Still having the same problem on the latest (1.14.1) the icon shows after entering the URL, but the disappear after saving. Tried it with local URL to my own nginx server and https://dashboardicons.com/icons/pgadmin.

Have you checked if there is a folder inside your logo directory? I had the same problem with the latest update and the problem was that the old version created a folder instead of an image file. The folder had the same name as the image file which are named after the OIDC client in Pocket-ID. E.g. something like `af8af299-f66a-4773-92dc-bf2e238acde9.svg`. 
I've solved it myself by just deleting this folder and trying it again in the ui.

**Comment by BobWs** [comment]
> > Still having the same problem on the latest (1.14.1) the icon shows after entering the URL, but the disappear after saving. Tried it with local URL to my own nginx server and https://dashboardicons.com/icons/pgadmin.
> 
> Have you checked if there is a folder inside your logo directory? I had the same problem with the latest update and the problem was that the old version created a folder instead of an image file. The folder had the same name as the image file which are named after the OIDC client in Pocket-ID. E.g. something like `af8af299-f66a-4773-92dc-bf2e238acde9.svg`. I've solved it myself by just deleting this folder and trying it again in the ui.

Thanks but no folders just the png files!

<img width="664" height="375" alt="Image" src="https://github.com/user-attachments/assets/6d193577-d7b6-4392-84e5-986fb6cfe9c9" />
