### ISSUE TITLE
🐛 Bug Report: Unable to select NFC when registering a passkey

### ISSUE THREAD

**Issue by Tagnard** [pocket-id/pocket-id#560]
### Reproduction steps

When I try to register a passkey I cannot select a NFC device, so I cannot use a Yubikey NFC on an android phone.

### Expected behavior

Display an option to use NFC when registering a passkey

### Actual Behavior

NFC option is not shown

### Version and Environment

v0.51.0

**Comment by Artemigos** [comment]
@RealOrangeOne Yeah, I was worried that this might be by design.

In the meantime, I experimented a little with <https://webauthn.io> on my phone. If I provide a username, I can register and authenticate with NFC fine. However, when I leave the username empty, the website still allows me to authenticate, but this time NFC is gone from options. This implies to me that in the "discoverable credentials" mode, NFC isn't supported by something up the chain.

This is just a guess (and a tangent) but seeing how, even when the user is known ahead of time, it takes a solid second or two of contact for NFC to work, this might actually be a transfer speed/reliability limitation of NFC itself.

**Comment by stonith404** [comment]
Could you test the `ghcr.io/pocket-id/pocket-id:development` image and let me know if the NFC option gets displayed?

**Comment by stonith404** [comment]
This should be fixed in `v.1.1.0`.

**Comment by stonith404** [comment]
Yeah @Artemigos I think you're right, I've found [this issue](https://issues.chromium.org/issues/328710551) which may be related. There isn't much we can do on Pocket ID's side. We are using the Webauthn API and we can control the passkey behavior with a few options but the actual passkey implementation is controlled by the Webauthn API.

**Comment by Artemigos** [comment]
@stonith404 nope, the `development` image doesn't change anything, NFC is still missing. I also updated my main instance to 1.2.0 and get the same result. Just in case I also tested with Chrome (was using Firefox previously) - no difference there.
