### ISSUE TITLE
🐛 Bug Report: Custom Claims on User Groups (and Users)

### ISSUE THREAD

**Issue by elcajon** [pocket-id/pocket-id#715]
### Reproduction steps

- Add 1-n custom claims to a user group --> works as expected
- Add 1-n custom claims to another user group --> not possible, "key" field is greyed out, left clicking the field shortly shows some values as suggestion (the ones entered in the first group)

- I also tried using the API to change an existing / create a new organization with the same results

### Expected behavior

Ability to add custom claims to multiple groups and users

### Actual Behavior

On a fresh installation it is only possible to enter custom claims to one user or user group.

<img width="1427" alt="Image" src="https://github.com/user-attachments/assets/14e82a12-2d18-414c-91c4-a9b78dab5ef7" />

<img width="1427" alt="Image" src="https://github.com/user-attachments/assets/2a3c996a-78d2-43df-8cff-7e7ecfcbd3fe" />

### Version and Environment

Docker compose (v1 and also next version) with Pangolin as reverse proxy.

### Log Output

Nothing special in the logs, I think: 
```
pocket-id-1  | [GIN] 2025/07/03 - 22:10:48 | 200 |     4.38208ms |  46.223.209.202 | GET      "/api/users?sort[column]=firstName&sort[direction]=asc"
pocket-id-1  | [GIN] 2025/07/03 - 22:10:48 | 200 |    2.792691ms |  46.223.209.202 | GET      "/api/signup-tokens?sort[column]=createdAt&sort[direction]=desc"
pocket-id-1  | [GIN] 2025/07/03 - 22:10:48 | 200 |    2.065398ms |  46.223.209.202 | GET      "/api/webauthn/credentials"
pocket-id-1  | [GIN] 2025/07/03 - 22:10:48 | 200 |    2.541127ms |  46.223.209.202 | GET      "/api/users/me"
pocket-id-1  | [GIN] 2025/07/03 - 22:10:49 | 200 |    4.154396ms |  46.223.209.202 | GET      "/api/user-groups?sort[column]=friendlyName&sort[direction]=asc"
pocket-id-1  | [GIN] 2025/07/03 - 22:10:52 | 200 |    3.034295ms |  46.223.209.202 | GET      "/api/user-groups/cc4a2a4c-bdb9-4265-ab6c-a0ce1f4c5e93"
pocket-id-1  | [GIN] 2025/07/03 - 22:10:52 | 200 |    3.074696ms |  46.223.209.202 | GET      "/api/users?sort[column]=firstName&sort[direction]=asc"
pocket-id-1  | [GIN] 2025/07/03 - 22:10:52 | 200 |    2.353043ms |  46.223.209.202 | GET      "/api/custom-claims/suggestions"
pocket-id-1  | [GIN] 2025/07/03 - 22:11:41 | 200 |    2.217761ms |  46.223.209.202 | GET      "/api/custom-claims/suggestions"
pocket-id-1  | [GIN] 2025/07/03 - 22:12:27 | 200 |    6.448518ms |  46.223.209.202 | GET      "/api/user-groups?sort[column]=friendlyName&sort[direction]=asc"
pocket-id-1  | [GIN] 2025/07/03 - 22:12:27 | 200 |    2.163559ms |  46.223.209.202 | GET      "/api/users/me"
pocket-id-1  | [GIN] 2025/07/03 - 22:12:27 | 200 |    3.436463ms |  46.223.209.202 | GET      "/api/webauthn/credentials"
pocket-id-1  | [GIN] 2025/07/03 - 22:12:32 | 200 |    3.417742ms |  46.223.209.202 | GET      "/api/user-groups/99b2b79d-d91b-42e4-9fe4-7e0e357c148a"
pocket-id-1  | [GIN] 2025/07/03 - 22:12:32 | 200 |    2.629408ms |  46.223.209.202 | GET      "/api/users?sort[column]=firstName&sort[direction]=asc"
pocket-id-1  | [GIN] 2025/07/03 - 22:12:32 | 200 |    1.714231ms |  46.223.209.202 | GET      "/api/custom-claims/suggestions"
```

**Comment by stonith404** [comment]
I can't reproduce this. Could you share a screen recording?

Do I understand correctly that in the second group you created, you can't enter anything into the "Key" input field, and the suggestions only appear for a short time before disappearing?

**Comment by elcajon** [comment]
> Do I understand correctly that in the second group you created, you can't enter anything into the "Key" input field, and the suggestions only appear for a short time before disappearing?

Exactly, the suggestions appear briefly when you left-click in the key field but then disappear again.

https://github.com/user-attachments/assets/b02a7a2b-f036-468b-a419-612fe441eccd

**Comment by stonith404** [comment]
Thanks for sharing the screen recording, this is really strange. Which browser are you using and are there any errors in the browser console?

**Comment by elcajon** [comment]
I tested using Safari (which I used for the screen recording) and Google Chrome on macOS (Tahoe dev beta and stable Sequoia).
There are no errors visible in either Chrome or Safari's console.

However, when I tested again, I noticed something else:

https://github.com/user-attachments/assets/bdbd4053-43a1-47e4-93d5-5b21049839c5

**Comment by elcajon** [comment]
FYI, I have just performed another test using a new Pocket ID installation (Docker Compose on clean Debian 12 Proxmox VM) and [Tailscale serve](https://tailscale.com/kb/1312/serve) as (VPN) proxy. Connecting via Ubuntu Desktop with Firefox browser yields the same results as previously reported.
Can you really not reproduce the error? If it helps, I could provide you access to my instance and infrastructure.

**Comment by stonith404** [comment]
Thank you for your detailed report. I was able to reproduce it in Safari, but strangely not in Brave which is also Chromium based. 

I'll look into it and let you know when it's fixed :)

**Comment by txwgnd** [comment]
Hi guys,

I was about to open an issue for this as well but I found yours. I have the exact same issue using Brave and Safari.
One thing to add from my side is that this also happens with the custom claims in the user settings. 

Cheers

**Comment by stonith404** [comment]
This should be fixed in 49f1ab2f75df97d551fff5acbadcd55df74af617 and will be available in the next release.

**Comment by elcajon** [comment]
Thanks a lot for the quick bugfix and also for the effort you put into this project. 😊

**Comment by elcajon** [comment]
Unfortunately, I have to come back to this. The latest changes have not fixed the error for me. Anything I can do to debug this further?

**Comment by stonith404** [comment]
That's strange, still on both browsers you have mentioned?

I'm on vacation so I can't look into it right now but I reopen it.

**Comment by elcajon** [comment]
Still on Safari and Brave.
The only difference I could spot is, that clicking the custom claim show/hide chevron (second video) no longer works around the issue.
Enjoy your holiday :)

**Comment by kmendell** [comment]
ill try to look into this while elias is away, ill let you know when i have something for testing

**Comment by kmendell** [comment]
@elcajon Can you try this image `ghcr.io/pocket-id/pocket-id:custom-claim-focus` and let me know if its fixed?

**Comment by elcajon** [comment]
Hey @kmendell , I just pulled the image. Unfortunately, it's still not working.
If it helps, I can provide access to my installation.

**Comment by kmendell** [comment]
What happens now when you try to add more than one? I was not able to reproduce it with this new logic, it let me add 3 different ones.

**Comment by elcajon** [comment]
I have recorded another short video. In general, adding tags now works. However, I have to add all the existing tags in order to create a new custom tag for the group:

https://github.com/user-attachments/assets/b764d0f7-f757-464e-b9ae-08244dff0b77

**Comment by shelldandy** [comment]
I have this issue too although im running the `app-dash` image

**Comment by ElioDiNino** [comment]
Also having this issue. I am using Chrome 138 on macOS.

**Comment by deancommasteven** [comment]
I was able to brute force adding a new claim after encountering this issue by quickly repeatedly clicking in the field and pasting. Eventually it overcomes whatever is going on. As soon as I delete one more character than is in the original claim key, the issue reappears. I can then overcome it again.

For me, the issue continues even after I've deleted the original claim key from any other location in Pocket ID.

v1.6.4

https://github.com/user-attachments/assets/9a437d33-6652-4cf5-b2d4-77e175e4982a

**Comment by pasarenicu** [comment]
Same here on. Pocket ID (1.6.4)

**Comment by cyndane31** [comment]
Encountered the same issue today on my laptop (Brave) and phone (Android Chrome).
Bypassed with right-click->Force Paste in Brave.

**Comment by stonith404** [comment]
Thanks for all the comments, this really helps to debug issues. 

This should be fixed in 4d59e7286666480e20c728787a95e82513509240 and will be available in the next release.

**Comment by elcajon** [comment]
Quick feedback on the issue. The update to v1.7.0 has fixed the problem. Thank you very much!
